site_name: Improse

pages:
- Home:
    - 'Quickstart': 'index.md'
- Basic usage:
    - 'Installation': 'basic/installation.md'
    - 'Views': 'basic/views.md'
    - 'Templates': 'basic/templates.md'

theme: united
